version: "3.9"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqldata:/var/opt/mssql
volumes:
  mssqldata:
    driver: local

